2021-05-25 13:18:49,921    DEBUG ---> Запуск client02.py   
2021-05-25 13:18:49,926    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:18:49,927    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621937929.927407', 'alert': 'Please connect'}   
2021-05-25 13:18:50,183    ERROR ---> Ran out of input   
2021-05-25 13:20:03,096    DEBUG ---> Запуск client02.py   
2021-05-25 13:20:03,098    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:20:03,098    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621938003.098485', 'alert': 'Please connect'}   
2021-05-25 13:20:10,540    ERROR ---> Ran out of input   
2021-05-25 13:29:13,997    DEBUG ---> Запуск client02.py   
2021-05-25 13:29:13,998    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:29:13,999    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621938553.9990633', 'alert': 'Please connect'}   
2021-05-25 13:29:17,788    ERROR ---> Ran out of input   
2021-05-25 13:33:39,579    DEBUG ---> Запуск client02.py   
2021-05-25 13:33:39,580    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:33:39,581    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621938819.580944', 'alert': 'Please connect'}   
2021-05-25 13:33:43,210    ERROR ---> Ran out of input   
2021-05-25 13:38:19,195    DEBUG ---> Запуск client02.py   
2021-05-25 13:38:19,197    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:38:19,197    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621939099.197446', 'alert': 'Please connect'}   
2021-05-25 13:38:19,715    ERROR ---> Ran out of input   
2021-05-25 13:43:01,141    DEBUG ---> Запуск client02.py   
2021-05-25 13:43:01,142    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:43:01,143    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621939381.143178', 'alert': 'Please connect'}   
2021-05-25 13:43:07,863    ERROR ---> Ran out of input   
2021-05-25 13:45:03,993    DEBUG ---> Запуск client02.py   
2021-05-25 13:45:03,995    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:45:03,995    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621939503.995383', 'alert': 'Please connect'}   
2021-05-25 13:45:11,416    ERROR ---> Ran out of input   
2021-05-25 13:47:31,060    DEBUG ---> Запуск client02.py   
2021-05-25 13:47:31,062    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:47:31,062    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621939651.0622728', 'alert': 'Please connect'}   
2021-05-25 13:47:38,791    ERROR ---> Ran out of input   
2021-05-25 13:49:41,872    DEBUG ---> Запуск client02.py   
2021-05-25 13:49:41,873    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:49:41,874    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621939781.8740137', 'alert': 'Please connect'}   
2021-05-25 13:49:45,208    ERROR ---> Ran out of input   
2021-05-25 13:54:15,691    DEBUG ---> Запуск client02.py   
2021-05-25 13:54:15,692    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:54:15,693    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621940055.6931849', 'alert': 'Please connect'}   
2021-05-25 13:54:23,291    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621940063.2907498', 'action': 'connect'}   
2021-05-25 13:54:40,599    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621940080.5989928', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 13:54:40,675    ERROR ---> Ran out of input   
2021-05-25 13:58:59,708    DEBUG ---> Запуск client02.py   
2021-05-25 13:58:59,709    DEBUG ---> Создаём экземпляр Client   
2021-05-25 13:58:59,710    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621940339.7101893', 'alert': 'Please connect'}   
2021-05-25 13:59:07,548    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621940347.5483253', 'action': 'connect'}   
2021-05-25 13:59:40,360    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621940380.3600137', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 13:59:40,479    ERROR ---> Ran out of input   
2021-05-25 14:10:23,758    DEBUG ---> Запуск client02.py   
2021-05-25 14:10:23,760    DEBUG ---> Создаём экземпляр Client   
2021-05-25 14:10:23,760    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621941023.7604978', 'alert': 'Please connect'}   
2021-05-25 14:10:30,584    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621941030.5842245', 'action': 'connect'}   
2021-05-25 14:10:45,144    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621941045.1437662', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 14:10:45,337    ERROR ---> Ran out of input   
2021-05-25 15:20:07,682    DEBUG ---> Запуск client02.py   
2021-05-25 15:20:07,683    DEBUG ---> Создаём экземпляр Client   
2021-05-25 15:20:07,683    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621945207.6836784', 'alert': 'Please connect'}   
2021-05-25 15:20:09,703    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621945209.7033467', 'action': 'connect'}   
2021-05-25 15:21:29,947    DEBUG ---> Запуск client02.py   
2021-05-25 15:21:29,949    DEBUG ---> Создаём экземпляр Client   
2021-05-25 15:21:29,949    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621945289.9493926', 'alert': 'Please connect'}   
2021-05-25 15:21:37,979    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621945297.9789546', 'action': 'connect'}   
2021-05-25 15:21:44,063    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621945304.063335', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-25 15:21:44,248    ERROR ---> Ran out of input   
2021-05-25 15:23:26,094    DEBUG ---> Запуск client02.py   
2021-05-25 15:23:26,096    DEBUG ---> Создаём экземпляр Client   
2021-05-25 15:23:26,096    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621945406.0962527', 'alert': 'Please connect'}   
2021-05-25 15:23:26,359    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621945406.359107', 'action': 'connect'}   
2021-05-25 15:23:31,290    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621945411.290284', 'user': {'login': 'I', 'pass': 'P'}}   
2021-05-25 15:23:31,413    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621945411.413221', 'action': 'authorization'}   
2021-05-25 16:05:15,967    DEBUG ---> Запуск client02.py   
2021-05-25 16:05:15,968    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:05:15,969    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621947915.9690218', 'alert': 'Please connect'}   
2021-05-25 16:05:22,841    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621947922.8416948', 'action': 'connect'}   
2021-05-25 16:05:29,102    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621947929.1022701', 'user': {'login': 'L', 'pass': 'Ведите пароль или N для выхода: '}}   
2021-05-25 16:05:29,313    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621947929.3128576', 'action': 'authorization'}   
2021-05-25 16:05:49,579    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621947929.3137953', 'user': {'login': 'L', 'pass': 'Ведите пароль или N для выхода: '}, 'msg': '1'}   
2021-05-25 16:08:20,163    DEBUG ---> Запуск client02.py   
2021-05-25 16:08:20,165    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:08:20,165    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621948100.1654823', 'alert': 'Please connect'}   
2021-05-25 16:08:23,572    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621948103.572375', 'action': 'connect'}   
2021-05-25 16:08:29,214    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621948109.2145467', 'user': {'login': 'Log', 'pass': 'Ведите пароль или N для выхода: '}}   
2021-05-25 16:08:29,240    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621948109.2399619', 'action': 'authorization'}   
2021-05-25 16:08:34,306    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621948109.2409625', 'user': {'login': 'Log', 'pass': 'Ведите пароль или N для выхода: '}, 'msg': '123'}   
2021-05-25 16:12:12,974    DEBUG ---> Запуск client02.py   
2021-05-25 16:12:12,976    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:12:12,976    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621948332.9763727', 'alert': 'Please connect'}   
2021-05-25 16:12:19,266    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621948339.266399', 'action': 'connect'}   
2021-05-25 16:12:24,419    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621948344.4190948', 'user': {'login': '\\q', 'pass': 'Ведите пароль или N для выхода: '}}   
2021-05-25 16:12:24,526    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621948344.5264528', 'action': 'authorization'}   
2021-05-25 16:13:12,174    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621948344.5274198', 'user': {'login': '\\q', 'pass': 'Ведите пароль или N для выхода: '}, 'msg': 'qqq'}   
2021-05-25 16:22:50,909    DEBUG ---> Запуск client02.py   
2021-05-25 16:22:50,910    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:22:50,910    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621948970.9108546', 'alert': 'Please connect'}   
2021-05-25 16:22:58,472    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621948978.472339', 'action': 'connect'}   
2021-05-25 16:23:04,218    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621948984.2182672', 'user': {'login': 'L', 'pass': 'P'}}   
2021-05-25 16:23:04,342    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621948984.3421493', 'action': 'authorization'}   
2021-05-25 16:23:07,334    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621948984.3431497', 'user': {'login': 'L', 'pass': 'P'}, 'msg': '1'}   
2021-05-25 16:24:10,406    DEBUG ---> Запуск client02.py   
2021-05-25 16:24:10,407    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:24:10,408    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949050.408031', 'alert': 'Please connect'}   
2021-05-25 16:24:12,246    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949052.2462065', 'action': 'connect'}   
2021-05-25 16:24:16,436    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621949056.4358244', 'user': {'login': 'L', 'pass': 'P'}}   
2021-05-25 16:24:16,498    ERROR ---> Ran out of input   
2021-05-25 16:24:21,436    DEBUG ---> Запуск client02.py   
2021-05-25 16:24:21,437    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:24:21,437    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949061.4376204', 'alert': 'Please connect'}   
2021-05-25 16:24:26,713    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949066.713144', 'action': 'connect'}   
2021-05-25 16:24:30,088    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621949070.0882587', 'user': {'login': 'T', 'pass': 'R'}}   
2021-05-25 16:24:30,160    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949070.160598', 'action': 'authorization'}   
2021-05-25 16:24:33,257    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621949070.1616302', 'user': {'login': 'T', 'pass': 'R'}, 'msg': '1'}   
2021-05-25 16:24:36,544    ERROR ---> [Errno 104] Connection reset by peer   
2021-05-25 16:26:49,005    DEBUG ---> Запуск client02.py   
2021-05-25 16:26:49,007    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:26:49,007    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949209.007353', 'alert': 'Please connect'}   
2021-05-25 16:26:52,165    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949212.1656396', 'action': 'connect'}   
2021-05-25 16:26:57,698    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621949217.697785', 'user': {'login': 'L', 'pass': 'O'}}   
2021-05-25 16:26:57,830    ERROR ---> Ran out of input   
2021-05-25 16:27:08,484    DEBUG ---> Запуск client02.py   
2021-05-25 16:27:08,485    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:27:08,486    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949228.485941', 'alert': 'Please connect'}   
2021-05-25 16:27:18,255    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949238.2549753', 'action': 'connect'}   
2021-05-25 16:27:22,105    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621949242.1055088', 'user': {'login': 'E', 'pass': 'E'}}   
2021-05-25 16:27:22,306    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949242.3063815', 'action': 'authorization'}   
2021-05-25 16:27:24,598    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621949242.3073912', 'user': {'login': 'E', 'pass': 'E'}, 'msg': '1'}   
2021-05-25 16:34:59,939    DEBUG ---> Запуск client02.py   
2021-05-25 16:34:59,940    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:34:59,940    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949699.9406035', 'alert': 'Please connect'}   
2021-05-25 16:35:03,627    ERROR ---> Ran out of input   
2021-05-25 16:38:05,536    DEBUG ---> Запуск client02.py   
2021-05-25 16:38:05,537    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:38:05,537    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949885.5378351', 'alert': 'Please connect'}   
2021-05-25 16:38:08,356    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949888.3559644', 'action': 'connect'}   
2021-05-25 16:38:12,615    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621949892.6150172', 'user': {'login': 'W', 'pass': 'W'}}   
2021-05-25 16:38:12,809    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949892.8091052', 'action': 'authorization'}   
2021-05-25 16:38:14,553    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621949892.810117', 'user': {'login': 'W', 'pass': 'W'}, 'msg': 'w'}   
2021-05-25 16:39:07,797    DEBUG ---> Запуск client02.py   
2021-05-25 16:39:07,799    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:39:07,799    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621949947.7992864', 'alert': 'Please connect'}   
2021-05-25 16:39:15,704    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621949955.7040195', 'action': 'connect'}   
2021-05-25 16:39:34,146    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621949974.146326', 'user': {'login': 'i', 'pass': 't'}}   
2021-05-25 16:39:34,299    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621949974.2986584', 'action': 'authorization'}   
2021-05-25 16:39:51,152    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621949974.2996929', 'user': {'login': 'i', 'pass': 't'}, 'msg': ''}   
2021-05-25 16:40:08,755    ERROR ---> [Errno 104] Connection reset by peer   
2021-05-25 16:41:12,462    DEBUG ---> Запуск client02.py   
2021-05-25 16:41:12,464    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:41:12,464    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950072.4643257', 'alert': 'Please connect'}   
2021-05-25 16:41:19,619    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950079.6189792', 'action': 'connect'}   
2021-05-25 16:41:23,743    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621950083.7430587', 'user': {'login': 'e', 'pass': 'e'}}   
2021-05-25 16:41:23,874    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950083.8738062', 'action': 'authorization'}   
2021-05-25 16:46:41,478    DEBUG ---> Запуск client02.py   
2021-05-25 16:46:41,479    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:46:41,480    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950401.4801223', 'alert': 'Please connect'}   
2021-05-25 16:46:47,472    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950407.4720056', 'action': 'connect'}   
2021-05-25 16:47:07,399    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621950427.3994374', 'user': {'login': '1', 'pass': '1'}}   
2021-05-25 16:47:07,477    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950427.4769793', 'action': 'authorization'}   
2021-05-25 16:47:22,167    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621950427.4779897', 'user': {'login': '1', 'pass': '1'}, 'msg': '1'}   
2021-05-25 16:47:36,833    ERROR ---> [Errno 104] Connection reset by peer   
2021-05-25 16:49:15,043    DEBUG ---> Запуск client02.py   
2021-05-25 16:49:15,044    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:49:15,044    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950555.0448263', 'alert': 'Please connect'}   
2021-05-25 16:49:21,404    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950561.4043944', 'action': 'connect'}   
2021-05-25 16:49:33,669    DEBUG ---> Запуск client02.py   
2021-05-25 16:49:33,670    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:49:33,673    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950573.673591', 'alert': 'Please connect'}   
2021-05-25 16:49:33,675    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950573.6750772', 'action': 'connect'}   
2021-05-25 16:49:41,769    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621950581.7691967', 'user': {'login': '4', 'pass': '4'}}   
2021-05-25 16:49:41,965    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950581.9647262', 'action': 'authorization'}   
2021-05-25 16:49:46,866    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621950586.866277', 'user': {'login': '4', 'pass': '5'}}   
2021-05-25 16:50:01,868    ERROR ---> [Errno 104] Connection reset by peer   
2021-05-25 16:53:25,605    DEBUG ---> Запуск client02.py   
2021-05-25 16:53:25,607    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:53:25,607    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950805.607451', 'alert': 'Please connect'}   
2021-05-25 16:53:27,355    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950807.3549285', 'action': 'connect'}   
2021-05-25 16:53:35,161    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621950815.1614668', 'user': {'login': 'q', 'pass': 'q'}}   
2021-05-25 16:53:35,241    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621950815.24102', 'action': 'authorization'}   
2021-05-25 16:53:40,537    DEBUG ---> Запуск client02.py   
2021-05-25 16:53:40,538    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:53:40,538    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950820.5388653', 'alert': 'Please connect'}   
2021-05-25 16:54:01,195    ERROR ---> [Errno 104] Connection reset by peer   
2021-05-25 16:55:01,580    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621950815.242042', 'user': {'login': 'q', 'pass': 'q'}, 'msg': ''}   
2021-05-25 16:55:01,581    ERROR ---> Ran out of input   
2021-05-25 16:55:10,861    DEBUG ---> Запуск client02.py   
2021-05-25 16:55:10,862    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:55:10,862    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621950910.8627243', 'alert': 'Please connect'}   
2021-05-25 16:55:17,009    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621950917.0097098', 'action': 'connect'}   
2021-05-25 16:55:24,253    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621950924.2533324', 'user': {'login': 'R', 'pass': 'R'}}   
2021-05-25 16:55:39,748    ERROR ---> Ran out of input   
2021-05-25 16:56:52,981    DEBUG ---> Запуск client02.py   
2021-05-25 16:56:52,982    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:56:52,983    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621951012.982938', 'alert': 'Please connect'}   
2021-05-25 16:56:59,176    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621951019.1760614', 'action': 'connect'}   
2021-05-25 16:57:02,569    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621951022.5690696', 'user': {'login': 'Q', 'pass': 'Q'}}   
2021-05-25 16:57:02,616    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621951022.6166108', 'action': 'authorization'}   
2021-05-25 16:57:06,456    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621951022.6176205', 'user': {'login': 'Q', 'pass': 'Q'}, 'msg': '1'}   
2021-05-25 16:58:33,569    DEBUG ---> Запуск client02.py   
2021-05-25 16:58:33,571    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:58:33,571    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621951113.5714436', 'alert': 'Please connect'}   
2021-05-25 16:58:38,308    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621951118.308723', 'action': 'connect'}   
2021-05-25 16:58:41,675    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621951121.6746697', 'user': {'login': 'P', 'pass': 'P'}}   
2021-05-25 16:58:41,751    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621951121.7513204', 'action': 'authorization'}   
2021-05-25 16:58:44,534    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621951121.7523873', 'user': {'login': 'P', 'pass': 'P'}, 'msg': 'q'}   
2021-05-25 16:59:50,357    DEBUG ---> Запуск client02.py   
2021-05-25 16:59:50,358    DEBUG ---> Создаём экземпляр Client   
2021-05-25 16:59:50,358    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621951190.3586628', 'alert': 'Please connect'}   
2021-05-25 16:59:55,838    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621951195.838502', 'action': 'connect'}   
2021-05-25 16:59:59,276    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621951199.2762668', 'user': {'login': '12', 'pass': '21'}}   
2021-05-25 16:59:59,310    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621951199.310024', 'action': 'authorization'}   
2021-05-25 17:00:07,764    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621951199.3110845', 'user': {'login': '12', 'pass': '21'}, 'msg': '1'}   
2021-05-25 17:00:16,099    ERROR ---> [Errno 104] Connection reset by peer   
2021-05-25 17:28:20,199    DEBUG ---> Запуск client02.py   
2021-05-25 17:28:20,200    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:28:20,201    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621952900.2011893', 'alert': 'Please connect'}   
2021-05-25 17:29:34,474    DEBUG ---> Запуск client02.py   
2021-05-25 17:29:34,476    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:29:34,476    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621952974.476477', 'alert': 'Please connect'}   
2021-05-25 17:31:11,729    DEBUG ---> Запуск client02.py   
2021-05-25 17:31:11,730    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:31:11,730    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621953071.7308512', 'alert': 'Please connect'}   
2021-05-25 17:31:25,907    ERROR ---> Ran out of input   
2021-05-25 17:34:21,795    DEBUG ---> Запуск client02.py   
2021-05-25 17:34:21,797    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:34:21,797    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621953261.797273', 'alert': 'Please connect'}   
2021-05-25 17:34:28,511    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621953268.5112069', 'action': 'connect'}   
2021-05-25 17:37:10,124    DEBUG ---> Запуск client02.py   
2021-05-25 17:37:10,125    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:37:10,126    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621953430.126244', 'alert': 'Please connect'}   
2021-05-25 17:37:18,454    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621953438.4540372', 'action': 'connect'}   
2021-05-25 17:37:23,666    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621953443.6660793', 'user': {'login': '32', 'pass': '32'}}   
2021-05-25 17:37:23,712    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621953443.7120967', 'action': 'authorization'}   
2021-05-25 17:37:28,519    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621953443.7132998', 'user': {'login': '32', 'pass': '32'}, 'msg': '1'}   
2021-05-25 17:43:41,753    DEBUG ---> Запуск client02.py   
2021-05-25 17:43:41,754    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:43:41,755    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621953821.755194', 'alert': 'Please connect'}   
2021-05-25 17:43:41,756    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621953821.7565262', 'action': 'connect'}   
2021-05-25 17:43:46,472    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621953826.4723792', 'user': {'login': 'q1', 'pass': 'q1'}}   
2021-05-25 17:43:46,610    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621953826.6102734', 'action': 'authorization'}   
2021-05-25 17:43:48,106    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621953826.6112962', 'user': {'login': 'q1', 'pass': 'q1'}, 'msg': 'q'}   
2021-05-25 17:56:43,006    DEBUG ---> Запуск client02.py   
2021-05-25 17:56:43,008    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:56:43,008    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621954603.0085025', 'alert': 'Please connect'}   
2021-05-25 17:56:48,167    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621954608.1673493', 'action': 'connect'}   
2021-05-25 17:56:53,289    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621954613.2894485', 'user': {'login': 'ER', 'pass': 'ER'}}   
2021-05-25 17:58:55,005    DEBUG ---> Запуск client02.py   
2021-05-25 17:58:55,006    DEBUG ---> Создаём экземпляр Client   
2021-05-25 17:58:55,007    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621954735.0071456', 'alert': 'Please connect'}   
2021-05-25 17:59:00,029    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621954740.029337', 'action': 'connect'}   
2021-05-25 17:59:05,081    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621954745.080991', 'user': {'login': '1', 'pass': '1'}}   
2021-05-25 17:59:18,630    ERROR ---> Ran out of input   
2021-05-25 18:01:14,237    DEBUG ---> Запуск client02.py   
2021-05-25 18:01:14,238    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:01:14,238    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621954874.2386324', 'alert': 'Please connect'}   
2021-05-25 18:01:20,723    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621954880.7230158', 'action': 'connect'}   
2021-05-25 18:01:39,051    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621954899.0511181', 'user': {'login': '2', 'pass': '2'}}   
2021-05-25 18:01:55,618    ERROR ---> Ran out of input   
2021-05-25 18:06:04,711    DEBUG ---> Запуск client02.py   
2021-05-25 18:06:04,712    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:06:04,713    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621955164.7130435', 'alert': 'Please connect'}   
2021-05-25 18:06:11,978    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621955171.9784126', 'action': 'connect'}   
2021-05-25 18:06:19,832    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621955179.8326666', 'user': {'login': '3', 'pass': '3'}}   
2021-05-25 18:06:19,859    ERROR ---> Ran out of input   
2021-05-25 18:08:10,330    DEBUG ---> Запуск client02.py   
2021-05-25 18:08:10,331    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:08:10,332    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621955290.3319385', 'alert': 'Please connect'}   
2021-05-25 18:08:18,542    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621955298.5425022', 'action': 'connect'}   
2021-05-25 18:08:22,829    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621955302.8295298', 'user': {'login': '4', 'pass': '4'}}   
2021-05-25 18:08:22,996    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621955302.9964871', 'action': 'authorization'}   
2021-05-25 18:08:30,351    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621955302.9974868', 'user': {'login': '4', 'pass': '4'}, 'msg': '4'}   
2021-05-25 18:08:47,972    ERROR ---> Ran out of input   
2021-05-25 18:32:25,505    DEBUG ---> Запуск client02.py   
2021-05-25 18:32:25,507    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:32:25,507    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621956745.5073092', 'alert': 'Please connect'}   
2021-05-25 18:32:30,778    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621956750.778025', 'action': 'connect'}   
2021-05-25 18:32:36,103    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621956756.1032257', 'user': {'login': '5', 'pass': '5'}}   
2021-05-25 18:32:36,241    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621956756.2407103', 'action': 'authorization'}   
2021-05-25 18:32:44,988    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621956756.2416992', 'user': {'login': '5', 'pass': '5'}, 'msg': 'Привет', 'nChat': '1'}   
2021-05-25 18:34:39,045    DEBUG ---> Запуск client02.py   
2021-05-25 18:34:39,046    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:34:39,047    ERROR ---> [Errno 111] Connection refused   
2021-05-25 18:37:42,739    DEBUG ---> Запуск client02.py   
2021-05-25 18:37:42,740    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:37:42,740    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621957062.74072', 'alert': 'Please connect'}   
2021-05-25 18:37:49,894    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621957069.8941681', 'action': 'connect'}   
2021-05-25 18:37:52,942    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621957072.9421337', 'user': {'login': '3', 'pass': '3'}}   
2021-05-25 18:37:53,135    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621957073.1346264', 'action': 'authorization'}   
2021-05-25 18:38:02,067    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621957073.1356056', 'user': {'login': '3', 'pass': '3'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:38:02,232    ERROR ---> Ran out of input   
2021-05-25 18:41:48,305    DEBUG ---> Запуск client02.py   
2021-05-25 18:41:48,307    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:41:48,307    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621957308.3073206', 'alert': 'Please connect'}   
2021-05-25 18:41:56,314    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621957316.3140488', 'action': 'connect'}   
2021-05-25 18:41:58,255    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621957318.2556496', 'user': {'login': '1', 'pass': '1'}}   
2021-05-25 18:41:58,342    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621957318.3424788', 'action': 'authorization'}   
2021-05-25 18:42:06,706    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621957318.3435388', 'user': {'login': '1', 'pass': '1'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:42:06,833    ERROR ---> Ran out of input   
2021-05-25 18:52:11,809    DEBUG ---> Запуск client02.py   
2021-05-25 18:52:11,811    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:52:11,811    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621957931.8115413', 'alert': 'Please connect'}   
2021-05-25 18:52:19,561    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621957939.5612257', 'action': 'connect'}   
2021-05-25 18:52:29,482    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621957949.4826343', 'user': {'login': '2', 'pass': '2'}}   
2021-05-25 18:52:29,665    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621957949.6652193', 'action': 'authorization'}   
2021-05-25 18:52:35,337    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621957949.666232', 'user': {'login': '2', 'pass': '2'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:52:35,531    ERROR ---> Ran out of input   
2021-05-25 18:55:06,481    DEBUG ---> Запуск client02.py   
2021-05-25 18:55:06,482    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:55:06,482    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621958106.482723', 'alert': 'Please connect'}   
2021-05-25 18:55:13,312    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621958113.3121817', 'action': 'connect'}   
2021-05-25 18:55:14,821    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621958114.8208487', 'user': {'login': '3', 'pass': '3'}}   
2021-05-25 18:55:14,937    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621958114.936766', 'action': 'authorization'}   
2021-05-25 18:56:59,964    DEBUG ---> Запуск client02.py   
2021-05-25 18:56:59,965    DEBUG ---> Создаём экземпляр Client   
2021-05-25 18:56:59,965    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621958219.9658337', 'alert': 'Please connect'}   
2021-05-25 18:57:06,058    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621958226.0579467', 'action': 'connect'}   
2021-05-25 18:57:09,338    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621958229.3387012', 'user': {'login': '4', 'pass': '4'}}   
2021-05-25 18:57:09,502    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621958229.502235', 'action': 'authorization'}   
2021-05-25 18:57:15,267    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621958229.5033133', 'user': {'login': '4', 'pass': '4'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 18:58:07,167    ERROR ---> Ran out of input   
2021-05-25 19:01:58,993    DEBUG ---> Запуск client02.py   
2021-05-25 19:01:58,994    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:01:58,994    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621958518.9947402', 'alert': 'Please connect'}   
2021-05-25 19:02:05,573    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621958525.5735562', 'action': 'connect'}   
2021-05-25 19:02:07,856    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621958527.8560188', 'user': {'login': '5', 'pass': '5'}}   
2021-05-25 19:02:08,005    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621958528.0052948', 'action': 'authorization'}   
2021-05-25 19:02:12,643    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621958528.0063667', 'user': {'login': '5', 'pass': '5'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 19:03:06,327    ERROR ---> Ran out of input   
2021-05-25 19:15:47,369    DEBUG ---> Запуск client02.py   
2021-05-25 19:15:47,370    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:15:47,370    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621959347.3705978', 'alert': 'Please connect'}   
2021-05-25 19:15:52,220    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959352.2201962', 'action': 'connect'}   
2021-05-25 19:15:54,486    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621959354.4858084', 'user': {'login': '6', 'pass': '6'}}   
2021-05-25 19:15:54,652    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959354.6526062', 'action': 'authorization'}   
2021-05-25 19:15:59,546    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621959354.6536665', 'user': {'login': '6', 'pass': '6'}, 'msg': '321', 'nChat': '1'}   
2021-05-25 19:16:20,458    ERROR ---> Ran out of input   
2021-05-25 19:19:30,866    DEBUG ---> Запуск client02.py   
2021-05-25 19:19:30,868    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:19:30,868    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621959570.868416', 'alert': 'Please connect'}   
2021-05-25 19:19:37,910    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959577.909976', 'action': 'connect'}   
2021-05-25 19:19:40,400    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621959580.399852', 'user': {'login': '7', 'pass': '7'}}   
2021-05-25 19:19:40,543    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959580.542824', 'action': 'authorization'}   
2021-05-25 19:19:46,975    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621959580.543866', 'user': {'login': '7', 'pass': '7'}, 'msg': '321', 'nChat': '1'}   
2021-05-25 19:20:11,109    ERROR ---> Ran out of input   
2021-05-25 19:23:27,832    DEBUG ---> Запуск client02.py   
2021-05-25 19:23:27,834    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:23:27,834    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621959807.8343308', 'alert': 'Please connect'}   
2021-05-25 19:23:35,286    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959815.2863564', 'action': 'connect'}   
2021-05-25 19:23:36,916    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621959816.9158993', 'user': {'login': '8', 'pass': '8'}}   
2021-05-25 19:23:37,111    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959817.1109135', 'action': 'authorization'}   
2021-05-25 19:23:41,066    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621959817.111843', 'user': {'login': '8', 'pass': '8'}, 'msg': '123', 'nChat': '1'}   
2021-05-25 19:23:52,838    DEBUG ---> Запуск client02.py   
2021-05-25 19:23:52,839    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:23:52,839    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621959832.8396049', 'alert': 'Please connect'}   
2021-05-25 19:23:52,841    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959832.8409228', 'action': 'connect'}   
2021-05-25 19:23:57,185    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621959837.1854732', 'user': {'login': '9', 'pass': '9'}}   
2021-05-25 19:23:57,293    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959837.2928958', 'action': 'authorization'}   
2021-05-25 19:24:02,762    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621959837.2938862', 'user': {'login': '9', 'pass': '9'}, 'msg': '456', 'nChat': '1'}   
2021-05-25 19:24:02,956    ERROR ---> Ran out of input   
2021-05-25 19:24:11,690    ERROR ---> Ran out of input   
2021-05-25 19:24:59,118    DEBUG ---> Запуск client02.py   
2021-05-25 19:24:59,119    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:24:59,119    ERROR ---> [Errno 111] Connection refused   
2021-05-25 19:25:29,082    DEBUG ---> Запуск client02.py   
2021-05-25 19:25:29,083    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:25:29,084    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621959929.083964', 'alert': 'Please connect'}   
2021-05-25 19:25:36,912    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621959936.912139', 'action': 'connect'}   
2021-05-25 19:25:40,369    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621959940.3688583', 'user': {'login': '10', 'pass': '10'}}   
2021-05-25 19:25:40,558    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621959940.5580378', 'action': 'authorization'}   
2021-05-25 19:25:44,494    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621959940.559018', 'user': {'login': '10', 'pass': '10'}, 'msg': '456', 'nChat': '1'}   
2021-05-25 19:25:44,604    ERROR ---> Ran out of input   
2021-05-25 19:31:06,894    DEBUG ---> Запуск client02.py   
2021-05-25 19:31:06,895    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:31:06,896    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621960266.8960526', 'alert': 'Please connect'}   
2021-05-25 19:31:13,834    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621960273.8343291', 'action': 'connect'}   
2021-05-25 19:31:16,944    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621960276.9437945', 'user': {'login': '13', 'pass': '13'}}   
2021-05-25 19:31:17,075    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621960277.075554', 'action': 'authorization'}   
2021-05-25 19:31:20,697    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621960277.076568', 'user': {'login': '13', 'pass': '13'}, 'msg': '567', 'nChat': '1'}   
2021-05-25 19:32:01,693    ERROR ---> Ran out of input   
2021-05-25 19:59:20,323    DEBUG ---> Запуск client02.py   
2021-05-25 19:59:20,325    DEBUG ---> Создаём экземпляр Client   
2021-05-25 19:59:20,325    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621961960.3256092', 'alert': 'Please connect'}   
2021-05-25 19:59:26,835    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621961966.8348398', 'action': 'connect', 'chat': None}   
2021-05-25 19:59:29,989    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621961969.9894543', 'user': {'login': '15', 'pass': '15'}}   
2021-05-25 19:59:30,075    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621961970.0753312', 'action': 'authorization', 'chat': None}   
2021-05-25 19:59:32,886    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621961970.0763283', 'user': {'login': '15', 'pass': '15'}, 'msg': '555', 'nChat': '1'}   
2021-05-25 19:59:32,916    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'time': '1621961972.916468', 'action': 'chat', 'chat': [{'user': '8', 'msg': '123'}, {'user': '13', 'msg': '567'}, {'user': '15', 'msg': '555'}]}   
2021-05-25 20:00:04,552    DEBUG ---> Запуск client02.py   
2021-05-25 20:00:04,553    DEBUG ---> Создаём экземпляр Client   
2021-05-25 20:00:04,554    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621962004.5541468', 'alert': 'Please connect'}   
2021-05-25 20:00:04,555    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621962004.5554943', 'action': 'connect', 'chat': None}   
2021-05-25 20:00:09,911    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621962009.9115558', 'user': {'login': '16', 'pass': '16'}}   
2021-05-25 20:00:10,020    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621962010.019851', 'action': 'authorization', 'chat': None}   
2021-05-25 20:00:16,562    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621962010.0208135', 'user': {'login': '16', 'pass': '16'}, 'msg': 'Привет', 'nChat': '1'}   
2021-05-25 20:00:16,692    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'time': '1621962016.6919909', 'action': 'chat', 'chat': [{'user': '8', 'msg': '123'}, {'user': '13', 'msg': '567'}, {'user': '15', 'msg': '555'}, {'user': '16', 'msg': 'Привет'}]}   
2021-05-25 20:07:12,919    DEBUG ---> Запуск client02.py   
2021-05-25 20:07:12,920    DEBUG ---> Создаём экземпляр Client   
2021-05-25 20:07:12,921    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'connect', 'time': '1621962432.9210958', 'alert': 'Please connect'}   
2021-05-25 20:07:19,593    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Готов к подключению', 'time': '1621962439.5934508', 'action': 'connect', 'chat': None}   
2021-05-25 20:07:34,845    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'authorization', 'time': '1621962454.8451056', 'user': {'login': 'Lexa', 'pass': 'pass'}}   
2021-05-25 20:07:34,955    DEBUG ---> Получено сообщение от сервера: 
{'response': 200, 'alert': 'Авторизация прошла успешно', 'time': '1621962454.955338', 'action': 'authorization', 'chat': None}   
2021-05-25 20:08:01,971    DEBUG ---> Отправлено сообщение серверу: 
{'action': 'chat', 'time': '1621962454.9564545', 'user': {'login': 'Lexa', 'pass': 'pass'}, 'msg': 'Привет!', 'nChat': '2'}   
2021-05-25 20:08:02,030    ERROR ---> Ran out of input   
