2021-05-21 18:01:19,848    DEBUG ---> Запуск server02.py   
2021-05-21 18:01:19,849    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:03:31,693    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621609411.6929944', 'alert': 'Please connect'}   
2021-05-21 18:03:31,693    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621609411.6936839', 'action': 'connect'}   
2021-05-21 18:04:08,997    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621609448.9973893', 'alert': 'Please connect'}   
2021-05-21 18:04:08,998    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621609448.9980185', 'action': 'connect'}   
2021-05-21 18:04:30,231    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621609470.2310882', 'alert': 'Please connect'}   
2021-05-21 18:04:30,231    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621609470.2317219', 'action': 'connect'}   
2021-05-21 18:07:15,135    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621609635.1357858', 'alert': 'Please connect'}   
2021-05-21 18:07:15,136    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621609635.1364222', 'action': 'connect'}   
2021-05-21 18:10:40,309    DEBUG ---> Запуск server02.py   
2021-05-21 18:10:40,311    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:10:43,526    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621609843.5265353', 'alert': 'Please connect'}   
2021-05-21 18:10:43,527    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621609843.527634', 'action': 'connect'}   
2021-05-21 18:11:50,465    DEBUG ---> Запуск server02.py   
2021-05-21 18:11:50,467    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:11:56,670    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621609916.6706045', 'alert': 'Please connect'}   
2021-05-21 18:11:56,671    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621609916.6714873', 'action': 'connect'}   
2021-05-21 18:14:27,532    DEBUG ---> Запуск server02.py   
2021-05-21 18:14:27,534    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:14:31,091    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621610071.0917857', 'alert': 'Please connect'}   
2021-05-21 18:14:31,092    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621610071.0926368', 'action': 'connect'}   
2021-05-21 18:17:21,803    DEBUG ---> Запуск server02.py   
2021-05-21 18:17:21,804    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:17:24,454    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621610244.4547749', 'alert': 'Please connect'}   
2021-05-21 18:17:24,455    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621610244.455661', 'action': 'connect'}   
2021-05-21 18:17:27,461    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621610247.461094', 'user': {'login': 'Д', 'pass': 'З'}}   
2021-05-21 18:17:27,464    DEBUG ---> Добавили нового пользователя в {'Д': 'З'}   
2021-05-21 18:17:27,466    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'authorization OK', 'time': '1621610247.466669', 'action': 'authorization'}   
2021-05-21 18:17:27,468    ERROR ---> Ran out of input   
2021-05-21 18:18:01,415    DEBUG ---> Запуск server02.py   
2021-05-21 18:18:01,416    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:18:09,978    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621610289.9784663', 'alert': 'Please connect'}   
2021-05-21 18:18:09,979    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621610289.9793615', 'action': 'connect'}   
2021-05-21 18:18:14,112    ERROR ---> Ran out of input   
2021-05-21 18:37:32,372    DEBUG ---> Запуск server02.py   
2021-05-21 18:37:32,374    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:37:36,443    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621611456.442979', 'alert': 'Please connect'}   
2021-05-21 18:37:36,443    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621611456.44361', 'action': 'connect'}   
2021-05-21 18:37:46,327    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621611466.3273697', 'user': {'login': 'Login', 'pass': 'Pass'}}   
2021-05-21 18:37:46,330    DEBUG ---> Добавили нового пользователя в {'Login': 'Pass'}   
2021-05-21 18:37:46,332    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'authorization OK', 'time': '1621611466.3327463', 'action': 'authorization'}   
2021-05-21 18:37:46,334    ERROR ---> Ran out of input   
2021-05-21 18:57:26,260    DEBUG ---> Запуск server02.py   
2021-05-21 18:57:26,262    DEBUG ---> Создаём экземпляр Server   
2021-05-21 18:57:28,815    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621612648.815061', 'alert': 'Please connect'}   
2021-05-21 18:57:28,815    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621612648.8157117', 'action': 'connect'}   
2021-05-21 18:57:34,685    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621612654.6847878', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-21 18:57:34,687    DEBUG ---> Добавили нового пользователя в {'Ivan': 'Pass'}   
2021-05-21 18:57:34,690    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'authorization OK', 'time': '1621612654.6903143', 'action': 'authorization'}   
2021-05-21 18:57:34,692    ERROR ---> Ran out of input   
2021-05-21 19:01:13,950    DEBUG ---> Запуск server02.py   
2021-05-21 19:01:13,952    DEBUG ---> Создаём экземпляр Server   
2021-05-21 19:01:17,213    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621612877.213121', 'alert': 'Please connect'}   
2021-05-21 19:01:17,213    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621612877.2137797', 'action': 'connect'}   
2021-05-21 19:01:24,512    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621612884.5117028', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-21 19:01:24,514    DEBUG ---> Кто-то подключается второй раз!   
2021-05-21 19:01:24,519    DEBUG ---> Отправлено сообщение клиенту:
{'response': 409, 'alert': 'Кто-то уже подключен под Вашим именем и паролем', 'time': '1621612884.519331', 'action': 'authorization'}   
2021-05-21 19:01:24,520    ERROR ---> Ran out of input   
2021-05-21 19:09:55,615    DEBUG ---> Запуск server02.py   
2021-05-21 19:09:55,617    DEBUG ---> Создаём экземпляр Server   
2021-05-21 19:09:57,595    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621613397.595521', 'alert': 'Please connect'}   
2021-05-21 19:09:57,596    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621613397.5961585', 'action': 'connect'}   
2021-05-21 19:10:04,845    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621613404.8454633', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-21 19:10:04,848    DEBUG ---> Клиент уже зарегистрирован, пароли не совпадают   
2021-05-21 19:10:04,851    DEBUG ---> Отправлено сообщение клиенту:
{'response': 402, 'alert': 'Пользователь с таким именем уже зарегистриован или Вы ввели не верный пароль', 'time': '1621613404.8508968', 'action': 'authorization'}   
2021-05-21 19:10:19,117    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621613419.117543', 'user': {'login': 'Ivan', 'pass': 'P'}}   
2021-05-21 19:10:19,120    DEBUG ---> Клиент уже зарегистрирован, пароли не совпадают   
2021-05-21 19:10:19,122    DEBUG ---> Отправлено сообщение клиенту:
{'response': 402, 'alert': 'Пользователь с таким именем уже зарегистриован или Вы ввели не верный пароль', 'time': '1621613419.1224182', 'action': 'authorization'}   
2021-05-21 19:10:28,158    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621613428.157842', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-21 19:10:28,160    DEBUG ---> Клиент уже зарегистрирован, пароли не совпадают   
2021-05-21 19:10:28,164    DEBUG ---> Отправлено сообщение клиенту:
{'response': 402, 'alert': 'Пользователь с таким именем уже зарегистриован или Вы ввели не верный пароль', 'time': '1621613428.163762', 'action': 'authorization'}   
2021-05-21 19:17:42,692    DEBUG ---> Запуск server02.py   
2021-05-21 19:17:42,694    DEBUG ---> Создаём экземпляр Server   
2021-05-21 19:17:46,561    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621613866.560887', 'alert': 'Please connect'}   
2021-05-21 19:17:46,561    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621613866.5615377', 'action': 'connect'}   
2021-05-21 19:17:53,105    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621613873.1049588', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-21 19:17:53,109    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'authorization OK', 'time': '1621613873.1088645', 'action': 'authorization'}   
2021-05-21 19:17:53,109    DEBUG ---> Клиент уже зарегистрирован   
2021-05-21 19:17:53,110    ERROR ---> 'passName'   
2021-05-21 19:20:19,435    DEBUG ---> Запуск server02.py   
2021-05-21 19:20:19,437    DEBUG ---> Создаём экземпляр Server   
2021-05-21 19:20:21,882    DEBUG ---> Клиент просит подключения:
{'action': 'connect', 'time': '1621614021.881859', 'alert': 'Please connect'}   
2021-05-21 19:20:21,882    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'Im ready to connect', 'time': '1621614021.8825254', 'action': 'connect'}   
2021-05-21 19:20:27,730    DEBUG ---> Клиент пробует авторизоваться:
{'action': 'authorization', 'time': '1621614027.7299454', 'user': {'login': 'Ivan', 'pass': 'Pass'}}   
2021-05-21 19:20:27,734    DEBUG ---> Отправлено сообщение клиенту:
{'response': 200, 'alert': 'authorization OK', 'time': '1621614027.733933', 'action': 'authorization'}   
2021-05-21 19:20:27,735    ERROR ---> Ran out of input   
